name: Computer Club at Western Michigan University
markdown: redcarpet
pygments: true
permalink: /:title/

admin:
  name: Webmaster
  email: webmaster@yakko.cs.wmich.edu

github: https://github.com/ccowmu/

gems:
- jekyll-compass
- jekyll-haml

exclude:
- Gemfile
- Gemfile.lock
